/* tslint:disable */
export const LOADS: any[] = [
    {
        "currentPage": 1,
        "items": [
            {
                "alternateNumber": "6063229",
                "bidPlaced": false,
                "commodity": "TREE & PLANT",
                'destination': {
                    "cityName": "Morris",
                    "countryName": "USA",
                    "latitude": 41.36735,
                    "longitude": -88.424746,
                    "number": 2,
                    "scheduledArrivalEarly": "2018-11-19T23:00:00",
                    "stateCode": "IL",
                    "zipCode": "60450",
                    "locationName": "First America Metal Corp.",
                    "locationAddress1": "1000 E. Armstrong St.",
                    "locationAddress2": "Test Line 2"
                },
                "distance": 2129.6,
                "distanceUnit": "mi",
                "equipmentType": "Van",
                "number": "6939122",
                "id": "2-1647612",
                "origin": {
                    "cityName": "Olympia",
                    "countryName": "USA",
                    "latitude": 46.944912,
                    "longitude": -123.05352,
                    "number": 1,
                    "scheduledArrivalEarly": "2018-11-19T07:00:00",
                    "stateCode": "WA",
                    "zipCode": "98512",
                    "locationName": "Tsuki Nursery, Inc",
                    "locationAddress1": '4920 Henderson Blvd. SE'
                },
                'salesRep': {
                    'name': 'Bradley Gore',
                    'email': 'Bradley.Gore@xpo.com',
                    'userName': 'bgore'
                },
                'stops': [
                    {
                        'cityName': 'Olympia',
                        'countryName': 'USA',
                        'latitude': 46.944912,
                        'longitude': -123.05352,
                        'number': 1,
                        'scheduledArrivalEarly': '2018-11-19T07:00:00',
                        'stateCode': 'WA',
                        'zipCode': '98512',
                        'locationName': 'Tsuki Nursery, Inc',
                        'locationAddress1': '4920 Henderson Blvd. SE'
                    },
                    {
                        'cityName': 'Morris',
                        'countryName': 'USA',
                        'latitude': 41.36735,
                        'longitude': -88.424746,
                        'number': 2,
                        'scheduledArrivalEarly': '2018-11-19T23:00:00',
                        'stateCode': 'IL',
                        'zipCode': '60450',
                        'locationName': 'First America Metal Corp.',
                        'locationAddress1': '1000 E. Armstrong St.',
                        'locationAddress2': 'Test Line 2'
                    }
                ],
                'weight': 15000.0,
                'weightUnit': 'LB',
                'dmpRate': 10.5,
                'ratePerDistance': 0.00,
                'isReviewed': false,
                'commodities': [
                    {
                        'commodityName': 'TREE & PLANT',
                        'quantity': 50,
                        'weight': 15000.0,
                        'weightUnit': 'LB',
                        'equipmentType': 'Van',
                        'totalDistance': 2129.6,
                        'distanceUnit': 'mi',
                        'orderNumber': '6939122'
                    }
                ],
                'isEligibleforBuyitNow': true,
                'isEligibleforPlaceBid': true,
                'bidStatus': 'PortalPlaceBid',
                'notes': [],
                'isHazmat': false,
                'isCPAT': false,
                'isSmartway': false,
                'isTSA': false,
                'isPIP': false,
                'isFAST': false,
                'isCSA': false,
                'isCustomsBroker': false,
                'isTWICcard': false,
                'isUIIAcard': false,
                'isDropAndHook': false,
                'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063219',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-19T23:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'GENERIC - LITHIA SPRINGS, GA',
                'locationAddress1': 'N/A'
            },
            'distance': 256.2,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6939112',
            'id': '2-1647602',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-19T07:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-19T07:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-19T23:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'GENERIC - LITHIA SPRINGS, GA',
                'locationAddress1': 'N/A'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 13.5,
            'ratePerDistance': 0.05,
            'isReviewed': true,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 256.2,
                'distanceUnit': 'mi',
                'orderNumber': '6939112'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': false,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063218',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-19T23:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'GENERIC - LITHIA SPRINGS, GA',
                'locationAddress1': 'N/A'
            },
            'distance': 256.2,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6939111',
            'id': '2-1647601',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-19T07:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-19T07:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-19T23:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'GENERIC - LITHIA SPRINGS, GA',
                'locationAddress1': 'N/A'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 13.5,
            'ratePerDistance': 0.05,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 256.2,
                'distanceUnit': 'mi',
                'orderNumber': '6939111'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063213',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-19T23:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'GENERIC - LITHIA SPRINGS, GA',
                'locationAddress1': 'N/A'
            },
            'distance': 256.2,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6939106',
            'id': '2-1647596',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-19T07:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-19T07:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-19T23:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'GENERIC - LITHIA SPRINGS, GA',
                'locationAddress1': 'N/A'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 13.5,
            'ratePerDistance': 0.05,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 256.2,
                'distanceUnit': 'mi',
                'orderNumber': '6939106'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063096',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-20T12:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 1.0,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938990',
            'id': '2-1647479',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-19T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-19T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-20T12:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 10.5,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 1.0,
                'distanceUnit': 'mi',
                'orderNumber': '6938990'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063020',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-20T12:00:00',
                'scheduledArrivalLate': '2021-05-13T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938915',
            'id': '2-1647415',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-19T12:00:00',
                'scheduledArrivalLate': '2018-12-19T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-19T12:00:00',
                'scheduledArrivalLate': '2018-12-19T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-20T12:00:00',
                'scheduledArrivalLate': '2021-05-13T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938915'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063019',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-19T12:00:00',
                'scheduledArrivalLate': '2021-05-12T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938914',
            'id': '2-1647414',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-18T12:00:00',
                'scheduledArrivalLate': '2018-12-18T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-18T12:00:00',
                'scheduledArrivalLate': '2018-12-18T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-19T12:00:00',
                'scheduledArrivalLate': '2021-05-12T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938914'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063018',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-18T12:00:00',
                'scheduledArrivalLate': '2021-05-11T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938913',
            'id': '2-1647413',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-17T12:00:00',
                'scheduledArrivalLate': '2018-12-17T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-17T12:00:00',
                'scheduledArrivalLate': '2018-12-17T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-18T12:00:00',
                'scheduledArrivalLate': '2021-05-11T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938913'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063017',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-16T12:00:00',
                'scheduledArrivalLate': '2021-05-09T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938912',
            'id': '2-1647412',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-15T12:00:00',
                'scheduledArrivalLate': '2018-12-15T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-15T12:00:00',
                'scheduledArrivalLate': '2018-12-15T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-16T12:00:00',
                'scheduledArrivalLate': '2021-05-09T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938912'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063014',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-13T12:00:00',
                'scheduledArrivalLate': '2021-05-06T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938909',
            'id': '2-1647409',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-12T12:00:00',
                'scheduledArrivalLate': '2018-12-12T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-12T12:00:00',
                'scheduledArrivalLate': '2018-12-12T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-13T12:00:00',
                'scheduledArrivalLate': '2021-05-06T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938909'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063013',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-12T12:00:00',
                'scheduledArrivalLate': '2021-05-05T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938908',
            'id': '2-1647408',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-11T12:00:00',
                'scheduledArrivalLate': '2018-12-11T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-11T12:00:00',
                'scheduledArrivalLate': '2018-12-11T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-12T12:00:00',
                'scheduledArrivalLate': '2021-05-05T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938908'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063012',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-11T12:00:00',
                'scheduledArrivalLate': '2021-05-04T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938907',
            'id': '2-1647407',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-10T12:00:00',
                'scheduledArrivalLate': '2018-12-10T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-10T12:00:00',
                'scheduledArrivalLate': '2018-12-10T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-11T12:00:00',
                'scheduledArrivalLate': '2021-05-04T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938907'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063011',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-09T12:00:00',
                'scheduledArrivalLate': '2021-05-02T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938906',
            'id': '2-1647406',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-08T12:00:00',
                'scheduledArrivalLate': '2018-12-08T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-08T12:00:00',
                'scheduledArrivalLate': '2018-12-08T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-09T12:00:00',
                'scheduledArrivalLate': '2021-05-02T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938906'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063010',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-08T12:00:00',
                'scheduledArrivalLate': '2021-05-01T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938905',
            'id': '2-1647405',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-07T12:00:00',
                'scheduledArrivalLate': '2018-12-07T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-07T12:00:00',
                'scheduledArrivalLate': '2018-12-07T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-08T12:00:00',
                'scheduledArrivalLate': '2021-05-01T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938905'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063009',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-07T12:00:00',
                'scheduledArrivalLate': '2021-04-30T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938904',
            'id': '2-1647404',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-06T12:00:00',
                'scheduledArrivalLate': '2018-12-06T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-06T12:00:00',
                'scheduledArrivalLate': '2018-12-06T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-07T12:00:00',
                'scheduledArrivalLate': '2021-04-30T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938904'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063008',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-06T12:00:00',
                'scheduledArrivalLate': '2021-04-29T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938903',
            'id': '2-1647403',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-05T12:00:00',
                'scheduledArrivalLate': '2018-12-05T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-05T12:00:00',
                'scheduledArrivalLate': '2018-12-05T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-06T12:00:00',
                'scheduledArrivalLate': '2021-04-29T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938903'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063007',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-05T12:00:00',
                'scheduledArrivalLate': '2021-04-28T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938902',
            'id': '2-1647402',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-04T12:00:00',
                'scheduledArrivalLate': '2018-12-04T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-04T12:00:00',
                'scheduledArrivalLate': '2018-12-04T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-05T12:00:00',
                'scheduledArrivalLate': '2021-04-28T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938902'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063006',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-04T12:00:00',
                'scheduledArrivalLate': '2021-04-27T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938901',
            'id': '2-1647401',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-03T12:00:00',
                'scheduledArrivalLate': '2018-12-03T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-03T12:00:00',
                'scheduledArrivalLate': '2018-12-03T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-04T12:00:00',
                'scheduledArrivalLate': '2021-04-27T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938901'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063005',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-02T12:00:00',
                'scheduledArrivalLate': '2021-04-25T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938900',
            'id': '2-1647400',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-01T12:00:00',
                'scheduledArrivalLate': '2018-12-01T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-12-01T12:00:00',
                'scheduledArrivalLate': '2018-12-01T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-02T12:00:00',
                'scheduledArrivalLate': '2021-04-25T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938900'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063004',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-01T12:00:00',
                'scheduledArrivalLate': '2021-04-24T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938899',
            'id': '2-1647399',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-30T12:00:00',
                'scheduledArrivalLate': '2018-11-30T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-30T12:00:00',
                'scheduledArrivalLate': '2018-11-30T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-12-01T12:00:00',
                'scheduledArrivalLate': '2021-04-24T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938899'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063003',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-30T12:00:00',
                'scheduledArrivalLate': '2021-04-23T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938898',
            'id': '2-1647398',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-29T12:00:00',
                'scheduledArrivalLate': '2018-11-29T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-29T12:00:00',
                'scheduledArrivalLate': '2018-11-29T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-30T12:00:00',
                'scheduledArrivalLate': '2021-04-23T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938898'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063002',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-29T12:00:00',
                'scheduledArrivalLate': '2021-04-22T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938897',
            'id': '2-1647397',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-28T12:00:00',
                'scheduledArrivalLate': '2018-11-28T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-28T12:00:00',
                'scheduledArrivalLate': '2018-11-28T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-29T12:00:00',
                'scheduledArrivalLate': '2021-04-22T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938897'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063001',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-28T12:00:00',
                'scheduledArrivalLate': '2021-04-21T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938896',
            'id': '2-1647396',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-27T12:00:00',
                'scheduledArrivalLate': '2018-11-27T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-27T12:00:00',
                'scheduledArrivalLate': '2018-11-27T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-28T12:00:00',
                'scheduledArrivalLate': '2021-04-21T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938896'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6063000',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-27T12:00:00',
                'scheduledArrivalLate': '2021-04-20T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938895',
            'id': '2-1647395',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-26T12:00:00',
                'scheduledArrivalLate': '2018-11-26T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-26T12:00:00',
                'scheduledArrivalLate': '2018-11-26T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-27T12:00:00',
                'scheduledArrivalLate': '2021-04-20T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938895'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            },
            {
            'alternateNumber': '6062999',
            'bidPlaced': false,
            'commodity': 'FOOD STUFFS',
            'destination': {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-25T12:00:00',
                'scheduledArrivalLate': '2021-04-18T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
            },
            'distance': 268.4,
            'distanceUnit': 'mi',
            'equipmentType': 'Van',
            'number': '6938894',
            'id': '2-1647394',
            'origin': {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-24T12:00:00',
                'scheduledArrivalLate': '2018-11-24T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
            },
            'salesRep': {
                'name': 'Bradley Gore',
                'email': 'Bradley.Gore@xpo.com',
                'userName': 'bgore'
            },
            'stops': [
                {
                'cityName': 'Charlotte',
                'countryName': 'USA',
                'latitude': 35.28457,
                'longitude': -80.733757,
                'number': 1,
                'scheduledArrivalEarly': '2018-11-24T12:00:00',
                'scheduledArrivalLate': '2018-11-24T12:00:00',
                'stateCode': 'NC',
                'zipCode': '28213',
                'locationName': 'Con-Tech Charlotte, NC',
                'locationAddress1': '1832 University Commercial Drive'
                },
                {
                'cityName': 'Lithia Springs',
                'countryName': 'USA',
                'latitude': 33.759169,
                'longitude': -84.64516,
                'number': 2,
                'scheduledArrivalEarly': '2018-11-25T12:00:00',
                'scheduledArrivalLate': '2021-04-18T00:00:00',
                'stateCode': 'GA',
                'zipCode': '30122',
                'locationName': 'FC: ATLANTA, GA #675',
                'locationAddress1': '7701 STAPLES DRIVE'
                }
            ],
            'weight': 100.0,
            'weightUnit': 'LB',
            'dmpRate': 10.5,
            'ratePerDistance': 0.04,
            'isReviewed': false,
            'commodities': [
                {
                'commodityName': 'FOOD STUFFS',
                'quantity': 75,
                'weight': 100.0,
                'weightUnit': 'LB',
                'equipmentType': 'Van',
                'totalDistance': 268.4,
                'distanceUnit': 'mi',
                'orderNumber': '6938894'
                }
            ],
            'isEligibleforBuyitNow': true,
            'isEligibleforPlaceBid': true,
            'bidStatus': 'PortalPlaceBid',
            'notes': [],
            'isHazmat': false,
            'isCPAT': false,
            'isSmartway': false,
            'isTSA': false,
            'isPIP': false,
            'isFAST': false,
            'isCSA': false,
            'isCustomsBroker': false,
            'isTWICcard': false,
            'isUIIAcard': false,
            'isDropAndHook': false,
            'equipmentCategory': 'Dry Van'
            }
        ],
        'pageSize': 25,
        'totalItemCount': 542,
        'totalPagesCount': 22
        }
];
